### ISSUE TITLE
[WINDOWS] Lack of optimization

### ISSUE THREAD

**Issue by xndrpr** [tsoding/musializer#32]
The program uses too many CPU for music. sometimes even 10% of my CPU, it's **even** more than Windows's anti malware. 
![image](https://github.com/tsoding/musializer/assets/98014243/bd488e41-a2d7-445e-8db5-a7b7ecd406f1)

Would be great to optimize the program to use less CPU

**Comment by rexim** [comment]
But does Window's anti malware visualize music?

**Comment by rexim** [comment]
On a serious note though, an empty Raylib app also consumes around 6% CPU for me on Linux. So far it does not cause any problems for me on my 10 years old laptop. I can even stream on Twitch while using this application.

But it would be nice to do some profiling and figure out the root cause. Feel free to do that.

**Comment by xndrpr** [comment]
> But does Window's anti malware visualize music?

Of course not XD Just kidding

**Comment by xndrpr** [comment]
> On a serious note though, an empty Raylib app also consumes around 6% CPU for me on Linux. So far it does not cause any problems for me on my 10 years old laptop. I can even stream on Twitch while using this application.
> 
> But it would be nice to do some profiling and figure out the root cause. Feel free to do that.

Then it's probably not your fault

**Comment by rexim** [comment]
> Then it's probably not your fault

Good!
