### ISSUE TITLE
[Thread] Collect all unsupported file formats

### ISSUE THREAD

**Issue by Mozart409** [tsoding/musializer#43]
Hi,

I wanted to start this thread to collect all unsupported sound formats.
So far I found following unsupported formats.
- m4a

**Comment by OetkenPurveyorOfCode** [comment]
There many audio file formats are out there e.g.: "s3m, stm, symmod, ahx, hvl, ay, vgz, vgm, mo3, ay, sid, psid, nsf, ...". Add them to your list. Let me know when you are done, then I will invent a new format, so that you will never finish :-)

IMHO: It is easier to list the supported file formats than listing all those that are not supported.
